create database customer_behaviour;
use customer_behaviour;

CREATE TABLE customer (
    Customer_ID INT,
    Age INT,
    Gender VARCHAR(10),
    Item_Purchased VARCHAR(100),
    Category VARCHAR(50),
    Purchase_Amount_USD INT,
    Location VARCHAR(100),
    Size VARCHAR(10),
    Color VARCHAR(50),
    Season VARCHAR(20),
    Review_Rating FLOAT,
    Subscription_Status VARCHAR(10),
    Shipping_Type VARCHAR(50),
    Discount_Applied VARCHAR(10),
    Promo_Code_Used VARCHAR(10),
    Previous_Purchases INT,
    Payment_Method VARCHAR(50),
    Frequency_of_Purchases VARCHAR(50)
);

select * from customer;

-- Q1. What is the total revenue generated by male vs. female customers?

select 
gender,sum(purchase_amount) total_amt 
from customer
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id, discount_applied ,purchase_amount
from customer
where discount_applied = "yes" and purchase_amount > (select avg(purchase_amount) from customer);

-- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased,round(avg(review_rating),2) average
from customer
group by item_purchased
order by average desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select  shipping_type,round(avg(purchase_amount),2) average
from customer
where shipping_type in ("Standard" , "Express")
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

select subscription_status,count(customer_id) total_customer,round(avg(purchase_amount),2) average,sum(purchase_amount) total
from customer
group by subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased,ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Suppose a group has 5 rows and discount_applied values are:
-- ['Yes', 'No', 'Yes', NULL, 'No']
-- CASE produces: [1, 0, 1, 0, 0] (NULL treated as ELSE → 0)
-- SUM(...) = 1 + 0 + 1 + 0 + 0 = 2
-- COUNT(*) = 5
-- SUM(...) / COUNT(*) = 2 / 5 = 0.4 → 40%

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 

SELECT customer_segment, COUNT(customer_segment) total_customer
FROM
    (SELECT customer_id,previous_purchases,
		CASE
			WHEN previous_purchases = 1 THEN 'New'
			WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returing'
			ELSE 'Loyal'
		END AS customer_segment
    FROM customer) AS a
GROUP BY customer_segment;

-- or

with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 

select * 
from
	(select * ,dense_rank() over(partition by category order by total_count desc) rnk 
    from
		(select 
			category,
			item_purchased,
			count(item_purchased) total_count
		from customer
		group by item_purchased,category)as a)as b
where rnk <= 3;

-- CTE

with a as(
select 
	category,
    item_purchased,
    count(item_purchased) total_qty,
    dense_rank()over(partition by category order by count(item_purchased) desc) rnk
from customer
group by category,item_purchased)
select * from a 
where rnk <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select count(customer_id) repeat_buyers,subscription_status
from customer
where previous_purchases > 5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group? 

select age_group,sum(purchase_amount) total_revenue
from customer
group by age_group
order by total_revenue desc;






